// @ts-ignore
import swaggerAutogen from "swagger-autogen";

const generator: any = swaggerAutogen();

const doc = {
    info: {
        version: "1.0.0",
        title: "Helpdesk API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ["http", "https"],
    consumes: ["application/json"],
    produces: ["application/json"],
    tags: [
        {
            name: "User",
            description: "Endpoints",
        },
    ],
    securityDefinitions: {
        apiKeyAuth: {
            type: "apiKey",
            in: "header", // can be "header", "query" or "cookie"
            name: "X-API-KEY", // name of the header, query parameter or cookie
            description: "any description...",
        },
    },
    definitions: {
        User: {
            name: "Jhon Doe",
            age: 29,
        },
    },
};

const outputFile = "src/api/docs/swagger.json";
const endpointsFiles = ["src/api/server.ts"];

generator(outputFile, endpointsFiles, doc).then(async () => {
    // eslint-disable-next-line global-require
    await require("../server");
});
